launchdarkly/SupportService

- docker-compose.yml
- run.sh
This script will make sure PostgreSQL is available before starting to run the app. 
It also removes the hard coded DB config.
> Move entrypoint into a script.

- app/config.py
- app/routes.py
- app/templates/beta/base.html
- app/templates/default/base.html
- docker-compose.yml
Updated the javascript LD SDK so that it no longer uses hard coded values for the front end feature flags.
> Use ENVAR For Front End SDK

- app/models.py
- app/routes.py
- app/templates/beta/beta.html
- app/templates/beta/entitlement.html
- app/templates/beta/exp.html
- app/templates/beta/index.html
- app/templates/beta/operation.html
- app/templates/beta/release.html
- app/templates/default/entitlement.html
- app/templates/default/exp.html
- app/templates/default/index.html
- app/templates/default/operation.html
- app/templates/default/release.html
- app/templates/main.html
- app/templates/partials/footer.html
- app/templates/partials/nav-dark.html
- app/templates/partials/nav.html
Templated out the files and folders to be more DRY. Removed the Bootstrap base as it was including jQuery and another file to be called twice causing javascript errors, which fixed the MetisMenu console error on the main pages. 
Dark Pages still utilizing majority of old code (albeit in slightly more templated fashion) and should be further optimized (including footer usage) and probably turned into Views so that the content for operation.html (for example) doesn't exist in two separate places. Certain JS errors still persist on Use Case Dark Pages. 
Also added "date" to model so that we can utilize date-based rollouts in demos.
> Templated branch

- webdriver/src/main/java/webdriver/App.java
- webdriver/src/main/java/webdriver/Randomizer.java
- webdriver/src/main/java/webdriver/Simulator.java
Simulate AB Tests results on the NPS Survey via the Simulator. 
Introduce a Randomizer class which will pseudo-randomly determine if a user should: 
* see an NPS survey 
* convert on an NPS survey 
The variation of the survey to be shown is determined by a feature flag.
> AB Testing Simulation

- cli.py
- cli/aws.py
- cli/templates/docker-compose.prod.jinja
- scripts/init.sh
This PR fixes a couple of bugs, and provides some more logging on how boxes are provisioned. There are still a few edge cases that I plan to flush out in the near term.
> Fix Some Bugs with Provisioning

- .circleci/config.yml
- cli.py
- cli/ld.py
This PR makes each deploy a separate CircleCI job. This allows us to deploy specific environments if needed and not have deployments be all or nothing.
> Split Up Deployment

- app/models.py
- app/routes.py
- app/templates/beta/auth/register.html
- app/templates/beta/base.html
- app/templates/default/base.html
- app/templates/home.html
- app/templates/partials/nav-dark.html
- app/templates/partials/nav.html
- cli/templates/docker-compose.prod.jinja
- scripts/deploy.sh
- webdriver/src/main/java/webdriver/Simulator.java
This PR implements a server side AB test. 
On the new home page, we will randomly serve one of two `trial_duration` variations (14, 30). If a user then signs up for a new account, we start tracking both the view rate, and completion rate of the registration form (`started-registration` and `registered`).
> Server Side AB Test

- README.md
- cli.py
- cli/templates/nginx.conf.jinja
- docker-compose.test.yml
- etc/nginx/nginx.test.conf
- scripts/deploy.sh
- webdriver/src/main/java/webdriver/App.java
This PR updates our TLD from `.tk` to `.org`. 
All sites will now be accessible via `http://$LAUNCHDARKY_ENVIRONMENT_KEY.ldsolutions.org`
> Change Demo TLD 

- .circleci/config.yml
- requirements.txt
Bump everything to latest major version. Bump CI caching key.
> ci: Update python dependencies

- app/config.py
Test user was not being created on startup.
> Fix query for test user

- .gitignore
- .vscode/extensions.json
Help onboard people easier by suggesting some extensions
> Suggest extensions for people new to the repo

- .circleci/config.yml
- tests/webdriver/src/main/java/webdriver/Simulator.java
> Check if element exists before trying to click

- .circleci/config.yml
- Makefile
- app/cli/generators.py
- app/cli/templates/nginx.conf.jinja
- app/config.py
- app/factory.py
- scripts/deploy_staging.sh
This PR will automatically deploy every commit outside of the master branch to the staging environment.
> ci: Deploy to Staging Environment

- .env.example
- Dockerfile.dev
- Makefile
- README.md
- docker-compose.yml
- scripts/start_dev.sh
This adds a new Docker dev environment: run the app inside Docker, but keep the source outside. Saves having to install Python and PostgreSQL, and futz with virtualenvs. Even better, it'll auto-restart the app when the source code changes.
Other tweaks:
* Suppress errors while app is waiting for db to start
* Remove `"export "` prefixes from `.env.example` (for docker-compose compat)
* Make main `Dockerfile` less sensitive to code changes
* Makefile: ensure use of Python3
* Minor README fixes
Done by @rmanalan and me.
> Docker dev environment (and other tweaks)

- .github/workflows/simulate.yml
This PR introduces a GH Actions workflow to execute our simulator.
> dev: Use Github Actions for simulator

- tests/webdriver/src/main/java/webdriver/App.java
This commit allows us to add the `nosim` tag to an environment in
LaunchDarkly which will cause the Simulator not to run against this
environment.
The purpose here is to only run the Simulator for environments where
people may actually be showing a demo.
Otherwise we are wasting both CI resources and cogs by having to index
many fake users whose data will never be used.
> webdriver: Run simulator for specific environments

- README.md
I ran into some confusion trying to access localhost:5000 and wanted to prevent anyone else from making the same mistake as I did :sweat_smile:
> Update README to point out including LD specific environment in local url

- app/factory.py
- app/routes.py
- app/templates/beta/base.html
- app/templates/main.html
- app/templates/partials/footer.html
- dev-requirements.txt
Javascript SDK was not bootstrapping, which can cause flashing issues on `show-widgets`.
The `ready` event was also not firing for all reloads. Switched that to `waitForInitialization` and it appears to be loading more consistently.
> core: Bootstrap SDK & Initialize callback

- app/models.py
- app/routes.py
- app/templates/home.html
- app/templates/main.html
- app/templates/partials/footer.html
- app/templates/partials/head.html
add accessibility flags to toggle button color, broken release
add ability to force a single page reload for broken release
> core: wrap delay in flag

- .circleci/config.yml
- app/admin_ldclient.py
- app/factory.py
- app/models.py
- app/routes.py
- scripts/deploy.sh
meta: Allows for SS to be run locally with a different provided project name.
core: Removed any options of caching.
> core: allow customized LD projects to be used

- .circleci/config.yml
- requirements.txt
- tests/test_basics.py
- tests/webdriver/src/main/java/webdriver/Simulator.java
@yozlet found issue with selenium running
> test: fix selenium

- tests/webdriver/src/main/java/webdriver/Simulator.java
Add wait time before register_link is clicked
> tests: add wait time for register_link

- app/templates/default/index.html
- app/templates/default/profile.html
- app/templates/main.html
There is an error in the integration when I don't use user ids that exist. This fixes that by using the user id when we know it.
> Adding user_id to amplitude

- .circleci/config.yml
- Dockerfile.ecr
- requirements.txt
Add ECR orb in the circle config file to deploy the "Dockerfile.ecr" to AWS ecr.
> config.yml: add aws-ecr orb for docker image deployment

- app/factory.py
This will handle the health checs performed by ALB
> core: handle responses to root directory

- .circleci/config.yml
Additional Circle jobs to deploy to staging and production with approval hold
> config.yml: add aws staging and codedeploy

- .github/workflows/push.yml
- .launchdarkly/coderefs.yaml
- app/routes.py
- app/templates/partials/footer.html
Add aliases for code refs scanning
> add alias examples
