launchdarkly/SupportService

.gitignore
LdLambda.py
Makefile
scripts/create_lambda.sh
scripts/package_lambda.sh
scripts/update_lambda.sh
setup.py

This function is currently deployed to lambda. When a new environment is created in LaunchDarkly, it will trigger a new deploy on CircleCI and automatically provision a new lightsail instance.

add lambda function to handle new environments

---

cli/templates/docker-compose.prod.jinja
cli/templates/nginx.conf.jinja

This PR adds a wildcard TLS certificate configuration to SupportService. The actual management of this certificate is handled on the server side, but this is the required configuration in order to get this to work properly.

Add letsencrypt TLS certificate.

---

app/routes.py

The function arguments were not named correctly when
instantiating the boto3 client. We are now using the correct
function argument names as described in the documentation.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client

Fix syntax error in boto client instantiation.

---

.circleci/config.yml

Python3.5 (the default version on the machine executor) was having some issues with our setup. I tried to solve it by installing Python3.6 with pyenv but this added 2+ minutes to every single build.
I tested everything out with Python2 and it works like a charm. This PR significantly reduces the build time for testing and creating new docker containers.

Speed Up Machine Build Step on CircleCI 

---

app/routes.py
app/util.py

Enables enriched data export metrics by tracking how long server rendering takes.

Configure artificial delay to showcase metrics

---

.env.example
app/config.py

Closes #69 
If `LD_RELAY_EVENTS_URL` or `LD_RELAY_STREAM_URL` is set use that value, otherwise it defaults to `base_uri`.

Use custom Env Vars if provided, otherwise fallback to default

---

.circleci/config.yml
Dockerfile
Dockerfile.dev
Makefile
app/cli/templates/docker-compose.prod.jinja
app/config.py
app/db.py
app/factory.py
app/ld.py
app/models.py
app/routes.py
app/util.py
dev-requirements.txt
docker-compose.yml
requirements.txt
scripts/start.sh
scripts/start_dev.sh
setup.py
tests/model_base.py
tests/test_basics.py
tests/test_model.py

Closes #75 
Previously every subdomain had a set of containers: web app, db, redis
This PR changes that logic so that there is only 3 containers total. The single flask app now performs subdomain dispatching based on LaunchDarkly environments. The environments are persisted into Redis.
Flask no longer performs the template generation logic. j2cli is now being used to create the docker-compose file.

Subdomain dispatcher

---

tests/webdriver/pom.xml
tests/webdriver/src/main/java/webdriver/App.java
tests/webdriver/src/main/java/webdriver/Simulator.java

This PR introduces a new permanent feature flag called
max-selenium-threads which allows us to specify the number of concurrent
tests to run when executing the selenium simulator.
This also bumps the version of Selenium to a more recent release which
fixed a bug where multiple versions of chrome were being launched.

webdriver: Make max threads configurable

---

.github/workflows/simulate.yml

This PR introduces a GH Actions workflow to execute our simulator.
Note. Using the `schedule` key appears to break GitHub actions. Switching to `push` for now, once this issue has been resolved I will submit another PR to introduce the schedule.

dev: Use Github actions for simulator

---

app/cli/templates/docker-compose.prod.jinja
scripts/start.sh

This commit increases max_connections to 10,000 and sets the number of
workers that gunicorn starts with to 5.

ops: Tune postgres and workers

---

app/models.py

This commit fixed an issue where we were indexing a bunch of GUID because the get_random_ld_user function did not set anonymous to true.

core: Stop indexing anonymous users

---

app/templates/beta/base.html
app/templates/default/base.html
app/templates/main.html

This will grant more control over JS SDK updates since the existing method is frozen at release 2.10.1. This will also add the support for experimentation's new functionalities

core: update JS SDK to using unpkg

---

app/config.py
app/factory.py

Flask's cached decorator was getting called too early, as it result it is access the "CACHE_TIMEOUT()" and "CachingDisabled()" feature flags. 
This is causing the ldclient to evaluate feature flags before its even initialized.
This change will allow the User class to be imported _after_ the flask instance is intialized.

core: fix early feature flag evaluation errors

---

app/admin_ldclient.py
app/cache.py
app/cli/templates/docker-compose.prod.jinja
app/config.py
app/factory.py
app/models.py
app/routes.py
scripts/deploy.sh

This PR has grown as issues have been encountered.
- Each Flask instance now has a proper client instantiated for that specific app to map to LaunchDarkly environment.
- Python Server SDK is now using Redis for feature store so there's a single view of the world from both containers.
- /environments webhook now works to provision new environments without having to do an app restart.
- Flask was creating an instance that would only return 404 if you tried to visit a subdomain before the key existed in Redis.
- There is now a global admin_ldclient tied to the `admin` environment of LaunchDarkly. This is to control global features like caching in blueprints. It can also be used in the automation of provisioning environments via the webhook above.

core: class instantiation, environment fixes

---

app/routes.py

temporary fix to disallow all environments to be able to access the `/environments` route.

core: add admin restriction to environments route

---

app/factory.py
app/routes.py

Add length to prefix so it doesn't clobber SDK keys when clearing

core: flush cache on plan change

---

app/routes.py
app/templates/default/base.html
app/templates/partials/nav.html

... for consistency with the flag name (which is currently "dark-theme" - maybe we should rename the flag to use an underscore).
The use of both `beta_features` and `show_beta` to represent a flag with yet another name is confusing when reading the code, and (more importantly) when trying to explain the code during a demo.

Rename beta_features/show_beta vars to dark_theme

---

app/templates/partials/footer.html

This test will track page load time for the show-widgets feature flag.
This test will be triggered whenever the /dashboard route is visited or refreshed.

core: add numeric experimentation test

---

app/templates/beta/auth/login.html
app/templates/beta/auth/register.html
app/templates/main.html

As the title states, this adds amplitude tracking for login pages as well as the main page and registration. Their sdk key works a lot like ours so it should be safe to just have in the client. This would be required to give people the synced amplitude endpoints.

added amplitude tracking for login/mainpage/registration

---

.circleci/config.yml

Previous ECS service "ss-blue-green" was not configured to support HTTPS target groups.
This is changing the circle orb to use the new CodeDeploy application for the new ECS service --> ss-production

circleci: change aws production deploy, add https target group

---

requirements.txt

This commit specifies a specific Werkzeug version to avoid the following error:
`ModuleNotFoundError: No module named 'werkzeug.posixemulation'`
This was happening on all requests on a fresh local install because Werkzeug was using the latest version (2.0.1 in my case). The posixemulation module was removed in 2.0.0, however, and it doesn't appear Flask was specifying a version to use. I included version 1.0.1 specifically because it was the last release prior to 2.0.0.

Dependencies: Specify Werkzeug version
